---@type table<integer, PacketDef>
local packets = {
	[1] = { id = 1, name = "Connect Request", valid = true },
	[2] = { id = 2, name = "Disconnect", valid = true },
	[3] = { id = 3, name = "Set User Slot", valid = true },
	[4] = { id = 4, name = "Player Info", valid = true },
	[5] = { id = 5, name = "Player Inventory Slot", valid = true },
	[6] = { id = 6, name = "Request World Data", valid = true },
	[7] = { id = 7, name = "World Info", valid = true },
	[8] = { id = 8, name = "Request Essential Tiles", valid = true },
	[9] = { id = 9, name = "Status", valid = true },
	[10] = { id = 10, name = "Send Section", valid = true },
	[11] = { id = 11, name = "Section Tile Frame", valid = true },
	[12] = { id = 12, name = "Spawn Player", valid = true },
	[13] = { id = 13, name = "Update Player", valid = true },
	[14] = { id = 14, name = "Player Active", valid = true },
	[15] = { id = 15, name = "Null", valid = false },
	[16] = { id = 16, name = "Player HP", valid = true },
	[17] = { id = 17, name = "Modify Tile", valid = true },
	[18] = { id = 18, name = "Time", valid = true },
	[19] = { id = 19, name = "Door Toggle", valid = true },
	[20] = { id = 20, name = "Send Tile Square", valid = true },
	[21] = { id = 21, name = "Update Item Drop", valid = true },
	[22] = { id = 22, name = "Update Item Owner", valid = true },
	[23] = { id = 23, name = "NPC Update", valid = true },
	[24] = { id = 24, name = "Strike NPCwith Held Item", valid = true },
	[25] = { id = 25, name = "Null", valid = false },
	[26] = { id = 26, name = "Null", valid = false },
	[27] = { id = 27, name = "Projectile Update", valid = true },
	[28] = { id = 28, name = "NPC Strike", valid = true },
	[29] = { id = 29, name = "Destroy Projectile", valid = true },
	[30] = { id = 30, name = "Toggle P V P", valid = true },
	[31] = { id = 31, name = "Open Chest", valid = true },
	[32] = { id = 32, name = "Update Chest Item", valid = true },
	[33] = { id = 33, name = "Sync Active Chest", valid = true },
	[34] = { id = 34, name = "PlaceChest", valid = true },
	[35] = { id = 35, name = "Heal Effect", valid = true },
	[36] = { id = 36, name = "Player Zone", valid = true },
	[37] = { id = 37, name = "Request Password", valid = true },
	[38] = { id = 38, name = "Send Password", valid = true },
	[39] = { id = 39, name = "Remove Item Owner", valid = true },
	[40] = { id = 40, name = "Set Active NPC", valid = true },
	[41] = { id = 41, name = "Player Item Animation", valid = true },
	[42] = { id = 42, name = "Player Mana", valid = true },
	[43] = { id = 43, name = "Mana Effect", valid = true },
	[44] = { id = 44, name = "Null", valid = false },
	[45] = { id = 45, name = "Player Team", valid = true },
	[46] = { id = 46, name = "Request Sign", valid = true },
	[47] = { id = 47, name = "Update Sign", valid = true },
	[48] = { id = 48, name = "Set Liquid", valid = true },
	[49] = { id = 49, name = "Complete Connection and Spawn", valid = true },
	[50] = { id = 50, name = "Update Player Buff", valid = true },
	[51] = { id = 51, name = "Special NPC Effect", valid = true },
	[52] = { id = 52, name = "Unlock", valid = true },
	[53] = { id = 53, name = "Add NPC Buff", valid = true },
	[54] = { id = 54, name = "Update NPC Buff", valid = true },
	[55] = { id = 55, name = "Add Player Buff", valid = true },
	[56] = { id = 56, name = "Update NPC Name", valid = true },
	[57] = { id = 57, name = "Update Good Evil", valid = true },
	[58] = { id = 58, name = "Play Music Item", valid = true },
	[59] = { id = 59, name = "Hit Switch", valid = true },
	[60] = { id = 60, name = "NPC Home Update", valid = true },
	[61] = { id = 61, name = "Spawn Boss Invasion", valid = true },
	[62] = { id = 62, name = "Player Dodge", valid = true },
	[63] = { id = 63, name = "Paint Tile", valid = true },
	[64] = { id = 64, name = "Paint Wall", valid = true },
	[65] = { id = 65, name = "Player NPC Teleport", valid = true },
	[66] = { id = 66, name = "Heal Other Player", valid = true },
	[67] = { id = 67, name = "Placeholder", valid = true },
	[68] = { id = 68, name = "Client UUID", valid = true },
	[69] = { id = 69, name = "Get Chest Name", valid = true },
	[70] = { id = 70, name = "Catch NPC", valid = true },
	[71] = { id = 71, name = "Release NPC", valid = true },
	[72] = { id = 72, name = "Travelling Merchant Inventory", valid = true },
	[73] = { id = 73, name = "Teleportation Potion", valid = true },
	[74] = { id = 74, name = "Angler Quest", valid = true },
	[75] = { id = 75, name = "Complete Angler Quest Today", valid = true },
	[76] = { id = 76, name = "Number Of Angler Quests Completed", valid = true },
	[77] = { id = 77, name = "Create Temporary Animation", valid = true },
	[78] = { id = 78, name = "Report Invasion Progress", valid = true },
	[79] = { id = 79, name = "Place Object", valid = true },
	[80] = { id = 80, name = "Sync Player Chest Index", valid = true },
	[81] = { id = 81, name = "Create Combat Text", valid = true },
	[82] = { id = 82, name = "Load Net Module", valid = true },
	[83] = { id = 83, name = "Set NPC Kill Count", valid = true },
	[84] = { id = 84, name = "Set Player Stealth", valid = true },
	[85] = { id = 85, name = "Force Item Into Nearest Chest", valid = true },
	[86] = { id = 86, name = "Update Tile Entity", valid = true },
	[87] = { id = 87, name = "Place Tile Entity", valid = true },
	[88] = { id = 88, name = "Tweak Item (FKA. Alter Item Drop)", valid = true },
	[89] = { id = 89, name = "Place Item Frame", valid = true },
	[90] = { id = 90, name = "Update Item Drop 2", valid = true },
	[91] = { id = 91, name = "Sync Emote Bubble", valid = true },
	[92] = { id = 92, name = "Sync Extra Value", valid = true },
	[93] = { id = 93, name = "Social Handshake", valid = true },
	[94] = { id = 94, name = "Deprecated", valid = true },
	[95] = { id = 95, name = "Kill Portal", valid = true },
	[96] = { id = 96, name = "Player Teleport Portal", valid = true },
	[97] = { id = 97, name = "Notify Player NPC Killed", valid = true },
	[98] = { id = 98, name = "Notify Player Of Event", valid = true },
	[99] = { id = 99, name = "Update Minion Target", valid = true },
	[100] = { id = 100, name = "NPC Teleport Portal", valid = true },
	[101] = { id = 101, name = "Update Shield Strengths", valid = true },
	[102] = { id = 102, name = "Nebula Level Up", valid = true },
	[103] = { id = 103, name = "Moon Lord Countdown", valid = true },
	[104] = { id = 104, name = "NPC Shop Item", valid = true },
	[105] = { id = 105, name = "Gem Lock Toggle", valid = true },
	[106] = { id = 106, name = "Poof of Smoke", valid = true },
	[107] = { id = 107, name = "Smart Text Message (FKA. Chat Message v2)", valid = true },
	[108] = { id = 108, name = "Wired Cannon Shot", valid = true },
	[109] = { id = 109, name = "Mass Wire Operation", valid = true },
	[110] = { id = 110, name = "Mass Wire Operation Consume", valid = true },
	[111] = { id = 111, name = "Toggle Birthday Party", valid = true },
	[112] = { id = 112, name = "GrowFX", valid = true },
	[113] = { id = 113, name = "CrystalInvasionStart", valid = true },
	[114] = { id = 114, name = "CrystalInvasionWipeAll", valid = true },
	[115] = { id = 115, name = "MinionAttackTargetUpdate", valid = true },
	[116] = { id = 116, name = "CrystalInvasionSendWaitTime", valid = true },
	[117] = { id = 117, name = "PlayerHurtV2", valid = true },
	[118] = { id = 118, name = "PlayerDeathV2", valid = true },
	[119] = { id = 119, name = "CombatTextString", valid = true },
	[120] = { id = 120, name = "Emoji", valid = true },
	[121] = { id = 121, name = "TEDisplayDollItemSync", valid = true },
	[122] = { id = 122, name = "RequestTileEntityInteraction", valid = true },
	[123] = { id = 123, name = "WeaponsRackTryPlacing", valid = true },
	[124] = { id = 124, name = "TEHatRackItemSync", valid = true },
	[125] = { id = 125, name = "SyncTilePicking", valid = true },
	[126] = { id = 126, name = "SyncRevengeMarker", valid = true },
	[127] = { id = 127, name = "RemoveRevengeMarker", valid = true },
	[128] = { id = 128, name = "LandGolfBallInCup", valid = true },
	[129] = { id = 129, name = "FinishedConnectingToServer", valid = true },
	[130] = { id = 130, name = "FishOutNPC", valid = true },
	[131] = { id = 131, name = "TamperWithNPC", valid = true },
	[132] = { id = 132, name = "PlayLegacySound", valid = true },
	[133] = { id = 133, name = "FoodPlatterTryPlacing", valid = true },
	[134] = { id = 134, name = "UpdatePlayerLuckFactors", valid = true },
	[135] = { id = 135, name = "DeadPlayer", valid = true },
	[136] = { id = 136, name = "SyncCavernMonsterType", valid = true },
	[137] = { id = 137, name = "RequestNPCBuffRemoval", valid = true },
	[138] = { id = 138, name = "ClientFinishedInventoryChangesOnThisTick (formerly ClientSyncedInventory)", valid = true },
	[139] = { id = 139, name = "SetCountsAsHostForGameplay", valid = true },
	[140] = { id = 140, name = "SetMiscEventValues", valid = true },
}

return packets
