---@class PacketDef
---@field id integer
---@field name string
---@field valid boolean

---@class UpdatePlayerFields
---@field root ProtoField
---@field player_id ProtoField
---@field control ProtoField
---@field pulley ProtoField
---@field misc ProtoField
---@field sleeping_info ProtoField
---@field selected_item ProtoField
---@field position ProtoField
---@field position_x ProtoField
---@field position_y ProtoField
---@field velocity ProtoField
---@field velocity_x ProtoField
---@field velocity_y ProtoField
---@field original_position ProtoField
---@field original_position_x ProtoField
---@field original_position_y ProtoField
---@field home_position ProtoField
---@field home_position_x ProtoField
---@field home_position_y ProtoField

---@class SendTileSquareFields
---@field root ProtoField
---@field header ProtoField
---@field encoded_size ProtoField
---@field size ProtoField
---@field tile_change_type ProtoField
---@field tile_x ProtoField
---@field tile_y ProtoField
---@field tiles ProtoField

---@class NpcUpdateFields
---@field root ProtoField
---@field npc_id ProtoField
---@field position ProtoField
---@field position_x ProtoField
---@field position_y ProtoField
---@field velocity ProtoField
---@field velocity_x ProtoField
---@field velocity_y ProtoField
---@field target ProtoField
---@field flags1 ProtoField
---@field flags2 ProtoField
---@field ai_group ProtoField
---@field ai ProtoField[]
---@field npc_net_id ProtoField
---@field difficulty_player_count ProtoField
---@field strength_multiplier ProtoField
---@field life_group ProtoField
---@field life_bytes ProtoField
---@field life ProtoField
---@field life_raw ProtoField
---@field release_owner ProtoField

---@class ProjectileUpdateFields
---@field root ProtoField
---@field projectile_id ProtoField
---@field position ProtoField
---@field position_x ProtoField
---@field position_y ProtoField
---@field velocity ProtoField
---@field velocity_x ProtoField
---@field velocity_y ProtoField
---@field owner ProtoField
---@field projectile_type ProtoField
---@field flags ProtoField
---@field ai_group ProtoField
---@field ai0 ProtoField
---@field ai1 ProtoField
---@field stats_group ProtoField
---@field damage ProtoField
---@field knockback ProtoField
---@field original_damage ProtoField
---@field projectile_uuid ProtoField

---@class UpdateItemDropFields
---@field root ProtoField
---@field item_id ProtoField
---@field position ProtoField
---@field position_x ProtoField
---@field position_y ProtoField
---@field velocity ProtoField
---@field velocity_x ProtoField
---@field velocity_y ProtoField
---@field item ProtoField
---@field stack_size ProtoField
---@field prefix ProtoField
---@field no_delay ProtoField
---@field item_net_id ProtoField

---@class TerrariaVector2
---@field x number
---@field y number

---@class TerrariaRangedVector2: TerrariaVector2
---@field range TvbRange
---@field x_range TvbRange
---@field y_range TvbRange

---@class TerrariaColor
---@field r integer
---@field g integer
---@field b integer

---@class TerrariaNetworkText
---@field mode integer
---@field text string
---@field substitutions TerrariaNetworkText[]
---@field mode_range TvbRange
---@field text_range TvbRange
---@field substitution_count integer
---@field substitution_count_range? TvbRange
---@field substitution_ranges TvbRange[]

---@class TerrariaChest
---@field id integer
---@field x integer
---@field y integer
---@field name string
---@field id_range TvbRange
---@field x_range TvbRange
---@field y_range TvbRange
---@field name_range TvbRange

---@class TerrariaSign
---@field id integer
---@field x integer
---@field y integer
---@field text string
---@field id_range TvbRange
---@field x_range TvbRange
---@field y_range TvbRange
---@field text_range TvbRange

---@class TerrariaItemData
---@field type integer
---@field prefix integer
---@field stack integer
---@field type_range TvbRange
---@field prefix_range TvbRange
---@field stack_range TvbRange

---@class TerrariaUpdateItemDrop
---@field item_id integer
---@field position TerrariaRangedVector2
---@field velocity TerrariaRangedVector2
---@field stack_size integer
---@field prefix integer
---@field no_delay integer
---@field item_net_id integer
---@field item_id_range TvbRange
---@field item_range TvbRange
---@field stack_size_range TvbRange
---@field prefix_range TvbRange
---@field no_delay_range TvbRange
---@field item_net_id_range TvbRange

---@class TerrariaParticleOrchestra
---@field position TerrariaVector2
---@field movement TerrariaVector2
---@field packed_shader_index integer
---@field invoking_player_id integer
---@field position_range TvbRange
---@field movement_range TvbRange
---@field packed_shader_index_range TvbRange
---@field invoking_player_id_range TvbRange

---@class TerrariaPlayerDeathReason
---@field flags integer
---@field killer_player_id? integer
---@field killer_npc_index? integer
---@field projectile_index? integer
---@field other_death_type? integer
---@field projectile_type? integer
---@field item_type? integer
---@field item_prefix? integer
---@field custom_reason? string
---@field flags_range TvbRange
---@field killer_player_id_range? TvbRange
---@field killer_npc_index_range? TvbRange
---@field projectile_index_range? TvbRange
---@field other_death_type_range? TvbRange
---@field projectile_type_range? TvbRange
---@field item_type_range? TvbRange
---@field item_prefix_range? TvbRange
---@field custom_reason_range? TvbRange

---@class TerrariaTile
---@field flags1 integer
---@field flags2 integer
---@field active boolean
---@field lighted boolean
---@field has_wall boolean
---@field has_liquid boolean
---@field wire1 boolean
---@field wire2 boolean
---@field wire3 boolean
---@field wire4 boolean
---@field half_brick boolean
---@field actuator boolean
---@field inactive boolean
---@field slope integer
---@field color? integer
---@field wall_color? integer
---@field type? integer
---@field frame_x? integer
---@field frame_y? integer
---@field wall? integer
---@field liquid? integer
---@field liquid_type? integer
---@field flags1_range TvbRange
---@field flags2_range TvbRange
---@field color_range? TvbRange
---@field wall_color_range? TvbRange
---@field type_range? TvbRange
---@field frame_x_range? TvbRange
---@field frame_y_range? TvbRange
---@field wall_range? TvbRange
---@field liquid_range? TvbRange
---@field liquid_type_range? TvbRange

---@class TerrariaTrainingDummyData
---@field npc_index integer
---@field npc_index_range TvbRange

---@class TerrariaLogicSensorData
---@field logic_check_type integer
---@field on boolean
---@field logic_check_type_range TvbRange
---@field on_range TvbRange

---@class TerrariaDisplayDollData
---@field item_flags integer
---@field dye_flags integer
---@field items TerrariaItemData[]
---@field dyes TerrariaItemData[]
---@field item_ranges TvbRange[]
---@field dye_ranges TvbRange[]
---@field item_flags_range TvbRange
---@field dye_flags_range TvbRange

---@class TerrariaHatRackData
---@field flags integer
---@field items TerrariaItemData[]
---@field dyes TerrariaItemData[]
---@field item_ranges TvbRange[]
---@field dye_ranges TvbRange[]
---@field flags_range TvbRange

---@alias TerrariaTileEntityExtraData TerrariaTrainingDummyData|TerrariaLogicSensorData|TerrariaDisplayDollData|TerrariaHatRackData|TerrariaItemData|table

---@class TerrariaTileEntity
---@field type integer
---@field id integer
---@field x integer
---@field y integer
---@field extra_data TerrariaTileEntityExtraData
---@field type_range TvbRange
---@field id_range TvbRange
---@field x_range TvbRange
---@field y_range TvbRange
---@field extra_data_range TvbRange

---@class TerrariaUpdatePlayer
---@field player_id integer
---@field control integer
---@field pulley integer
---@field misc integer
---@field sleeping_info integer
---@field selected_item integer
---@field position TerrariaRangedVector2
---@field velocity? TerrariaRangedVector2
---@field original_position? TerrariaRangedVector2
---@field home_position? TerrariaRangedVector2
---@field player_id_range TvbRange
---@field control_range TvbRange
---@field pulley_range TvbRange
---@field misc_range TvbRange
---@field sleeping_info_range TvbRange
---@field selected_item_range TvbRange

---@class TerrariaSendTileSquare
---@field encoded_size integer
---@field size integer
---@field tile_change_type? integer
---@field tile_x integer
---@field tile_y integer
---@field tiles? string
---@field encoded_size_range TvbRange
---@field header_range TvbRange
---@field tile_change_type_range? TvbRange
---@field tile_x_range TvbRange
---@field tile_y_range TvbRange
---@field tiles_range? TvbRange

---@class TerrariaNpcUpdate
---@field npc_id integer
---@field position TerrariaRangedVector2
---@field velocity TerrariaRangedVector2
---@field target integer
---@field flags1 integer
---@field flags2 integer
---@field ai number[]
---@field ai_ranges TvbRange[]
---@field ai_range? TvbRange
---@field npc_net_id integer
---@field difficulty_player_count? integer
---@field strength_multiplier? number
---@field life_bytes? integer
---@field life? integer
---@field life_raw? string
---@field life_group_range? TvbRange
---@field release_owner? integer
---@field npc_id_range TvbRange
---@field target_range TvbRange
---@field flags1_range TvbRange
---@field flags2_range TvbRange
---@field npc_net_id_range TvbRange
---@field difficulty_player_count_range? TvbRange
---@field strength_multiplier_range? TvbRange
---@field life_bytes_range? TvbRange
---@field life_range? TvbRange
---@field life_raw_range? TvbRange
---@field release_owner_range? TvbRange

---@class TerrariaProjectileUpdate
---@field projectile_id integer
---@field position TerrariaRangedVector2
---@field velocity TerrariaRangedVector2
---@field owner integer
---@field projectile_type integer
---@field flags integer
---@field ai0? number
---@field ai1? number
---@field damage? integer
---@field knockback? number
---@field original_damage? integer
---@field projectile_uuid? integer
---@field ai_range? TvbRange
---@field stats_range? TvbRange
---@field projectile_id_range TvbRange
---@field owner_range TvbRange
---@field projectile_type_range TvbRange
---@field flags_range TvbRange
---@field ai0_range? TvbRange
---@field ai1_range? TvbRange
---@field damage_range? TvbRange
---@field knockback_range? TvbRange
---@field original_damage_range? TvbRange
---@field projectile_uuid_range? TvbRange
